# solution_designer_test.yml

input_data:
  discovery_data:
    raw_output: |
      def calculate_total(items):
          total = 0
          for item in items:
              total += item['price']
          return total

      def apply_discount(total, discount_percent):
          return total * (1 - discount_percent/100)

      def process_order(items, discount=0):
          total = calculate_total(items)
          if discount > 0:
              total = apply_discount(total, discount)
          print(f"Order total: ${total:.2f}")
          return total
    files:
      "sample.py": true
    
  intent:
    description: |
      Modernize the code with:
      1. Replace manual loop with sum() and generator expression
      2. Add type hints
      3. Add parameter docstrings
      4. Replace print with logging
      5. Add input validation

format: "json"